version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/src
    ports:
      - "4001:4001"
  agent:
    image: grafana/agent:v0.21.2
    volumes:
    - "/tmp/agent:/etc/agent/data"
    - "${PWD}/grafana-agent-config.yaml:/etc/agent/agent.yaml"
    network_mode: host

  configure-env:
    image: grafana/agentctl:v0.21.2
    command: cloud-config --stack="$GCLOUD_STACK_ID" --api-key="$GCLOUD_API_KEY" --api-url="$GCLOUD_API_URL"
    profiles: ["setup"]
